### ISSUE TITLE
Problem with creating a better-labeled graph when Windows user name has a space

### ISSUE THREAD

**Issue by bbachilles** [mdroste/stata-binscatter2#11]
Hello Mike,

This is a fantastic update to binscatter. Thanks for sharing it with the world! I ran into a problem because I have a windows username that unfortunately has a space in it corresponding to my "Firstname Lastname". This has cause issues with other user-written Stata packages. Below is a the last bit of a trace from running the final example in the helpfile, with the error at the end. To be clear the original command was as follos (note that if I run this as binscatter wage age... instead of binscatter2 wage age, I get no problem:

 binscatter2 wage age, by(race) absorb(occupation) msymbols(O T)
            xtitle(Age) ytitle(Hourly Wage) legend(lab(1 White) lab(2 Black))

  ------------------------------------------------------------------- end reg ---
- }
- else {
  capture noisily reg `depvar' `regressor_list' `wt' if `conds'
  }
- if _rc==0 matrix e_b_temp=e(b)
- else if _rc==2000 {
  if("`reg_verbosity'"=="quietly" di as error "No observations for one of the fit
>  lines. add 'reportreg' for more info."
  if "`linetype'"=="lfit" matrix e_b_temp = J(1,2,.)
  if "`linetype'"=="logfit" matrix e_b_temp = J(1,2,.)
  if "`linetype'"=="expfit" matrix e_b_temp = J(1,2,.)
  else matrix e_b_temp = J(1,3,.)
  }
- else {
  exit _rc
  }
- if ("`by'"!="") matrix roweq e_b_temp = "by`counter_by'"
= if ("race"!="") matrix roweq e_b_temp = "by2"
- if ("`rd'"!="") matrix rownames e_b_temp = "rd`counter_rd'"
= if (""!="") matrix rownames e_b_temp = "rd1"
- else matrix rownames e_b_temp = "="
- if `counter_by'==1 & `counter_rd'==1 {
= if 2==1 & 1==1 {
  matrix `y`counter_depvar'_coefs' = e_b_temp
  }
- else {
- matrix `y`counter_depvar'_coefs' = `y`counter_depvar'_coefs' \ e_b_temp
= matrix __000006 = __000006 \ e_b_temp
- }
- local ++counter_depvar
- }
- if `counter_rd'!=1 mac shift
= if 1!=1 mac shift
- local ++counter_rd
- }
- while ("`1'"!="" | `counter_rd'==1) {
= while (""!="" | 2==1) {
  if "`reportreg'"!="" {
  di "{txt}{hline}"
  if "`by'"!="" {
  if ("`bylabel'"=="") di "-> `byvarname' = `byval'"
  else {
  di "-> `byvarname' = `: label `bylabel' `byval''"
  }
  }
  if "`rd'"!="" {
  if `counter_rd'==1 di "RD: `x_var'<=`1'"
  else if "`2'"!="" di "RD: `x_var'>`1' & `x_var'<=`2'"
  else di "RD: `x_var'>`1'"
  }
  }
  local conds `touse'
  if "`by'"!="" local conds `conds' & `by'==`byval'
  if "`rd'"!="" {
  if `counter_rd'==1 local conds `conds' & `x_r'<=`1'
  else if "`2'"!="" local conds `conds' & `x_r'>`1' & `x_r'<=`2'
  else local conds `conds' & `x_r'>`1'
  }
  local counter_depvar=1
  foreach depvar of varlist `y_vars_r' {
  if `ynum'>1 {
  if "`controls'`absorb'"!="" local depvar_name : var label `depvar'
  else local depvar_name `depvar'
  di as text "{bf:y_var = `depvar_name'}"
  }
  if "`reg_verbosity'"=="quietly" {
  capture reg `depvar' `x_r2' `x_r' `wt' if `conds', noheader notable
  }
  else {
  capture noisily reg `depvar' `regressor_list' `wt' if `conds'
  }
  if _rc==0 matrix e_b_temp=e(b)
  else if _rc==2000 {
  if("`reg_verbosity'"=="quietly" di as error "No observations for one of the fit
>  lines. add 'reportreg' for more info."
  if "`linetype'"=="lfit" matrix e_b_temp = J(1,2,.)
  if "`linetype'"=="logfit" matrix e_b_temp = J(1,2,.)
  if "`linetype'"=="expfit" matrix e_b_temp = J(1,2,.)
  else matrix e_b_temp = J(1,3,.)
  }
  else {
  exit _rc
  }
  if ("`by'"!="") matrix roweq e_b_temp = "by`counter_by'"
  if ("`rd'"!="") matrix rownames e_b_temp = "rd`counter_rd'"
  else matrix rownames e_b_temp = "="
  if `counter_by'==1 & `counter_rd'==1 {
  matrix `y`counter_depvar'_coefs' = e_b_temp
  }
  else {
  matrix `y`counter_depvar'_coefs' = `y`counter_depvar'_coefs' \ e_b_temp
  }
  local ++counter_depvar
  }
  if `counter_rd'!=1 mac shift
  local ++counter_rd
  }
- local ++counter_by
- }
- if "`ci'"!="" {
= if ""!="" {
  predictnl = predict(), ci(ci3 ci4)
  }
- forvalues i=1/`ynum' {
= forvalues i=1/1 {
- if "`linetype'"=="lfit" {
= if "lfit"=="lfit" {
- matrix colnames `y`i'_coefs' = "`x_var'" "_cons"
= matrix colnames __000006 = "age" "_cons"
- }
- else if "`linetype'"=="qfit" {
= else if "lfit"=="qfit" {
  matrix colnames `y`i'_coefs' = "`x_var'^2" "`x_var'" "_cons"
  }
- }
- }
- local collapsetype mean
- if "`medians'"!="" local collapsetype median
= if ""!="" local collapsetype median
- if "`quantiles'"!="" {
= if ""!="" {
  local current_quantile 1
  foreach v in `quantiles' {
  local q`current_quantile' = `v'
  local current_quantile = `current_quantile' + 1
  }
  local quantiles_opt "(p`q1') p`q1'=`y_vars_r' (p`q2') p`q2'=`y_vars_r'"
  local quantile_vars p`q1' p`q2'
  }
- if `stdevs'!=-1 {
= if -1!=-1 {
  tempvar sd
  local quantiles_opt "(sd) `sd' =`y_vars_r'"
  }
- if "`by'"=="" {
= if "race"=="" {
  qui drop if `xq'==.
  gcollapse (`collapsetype') `y_vars_r' `x_r' `quantiles_opt', by(`xq') fast
  local counter_depvar=0
  foreach depvar of varlist `y_vars_r' {
  local ++counter_depvar
  tempname y`counter_depvar'_scatterpts
  mkmat `x_r' `depvar', mat(`y`counter_depvar'_scatterpts')
  }
  if "`quantiles'"!="" {
  if `c(stata_version)' >= 15.0 local opacity %40
  local quantile_macro (rarea p`q2' p`q1' `x_r', color(gs12`opacity'))
  }
  if `stdevs'>-1 {
  if `c(stata_version)' >= 15.0 local opacity %40
  tempvar sd_ub sd_lb
  gen `sd_ub' = `y_vars_r' + `stdevs'*`sd'
  gen `sd_lb' = `y_vars_r' - `stdevs'*`sd'
  local quantile_macro (rarea `sd_ub' `sd_lb' `x_r', color(gs12`opacity'))
  }
  }
- if "`by'"!="" {
= if "race"!="" {
- tempfile t1
- qui save `t1'
= qui save C:\Users\Erik Lastname\AppData\Local\Temp\ST_3540_000002.tmp
invalid 'Lastname' 
  local by_counter = 0
  qui foreach byval in `byvals' `noby' {
  local by_counter = `by_counter' + 1
  qui keep if `by'==`byval'
  qui drop if `xq'==.
  gcollapse `y_vars_r' `x_r', by(`xq') fast
  global counter_depvar=0
  foreach depvar of varlist `y_vars_r' {
  global counter_depvar = $counter_depvar + 1
  local c1 = $counter_depvar
  local c2 = `by_counter'
  tempname y`c1'_scatterpts
  mkmat `x_r' `depvar', mat(temp`c2'_`c1')
  }
  use `t1', clear
  }
  forval i=1/$counter_depvar {
  mat `y`i'_scatterpts' = temp1_`i'
  if `by_counter'>1 {
  forval j=2/`by_counter' {
  mat `y`i'_scatterpts' = `y`i'_scatterpts',temp`j'_`i'
  }
  }
  }
  }
------------------------------------------------------------- end binscatter2 ---
r(198);

**Comment by mdroste** [comment]
Hi there! This should be fixed in the latest version I'm pushing today (0.25)
