### ISSUE TITLE
Twoway options no longer working

### ISSUE THREAD

**Issue by SantiagoCantilloCleves** [mdroste/stata-binscatter2#14]
Hi, I think the last update might have generated a problem with twoway options. The following example worked before but no longer works.
```
which binscatter2 
sysuse auto
binscatter2 price mpg ,  title("Price vs MPG")
```
I get error code r(198) "option title() not allowed". I'm using Binscatter2 version 0.90 (05dec2022).
Do I have something wrong or is this a bug?
Thanks!

**Comment by mdroste** [comment]
Totally my fault! Thanks for raising this. Fixed now. Please update by reinstalling. Thanks for pointing this out!
