### ISSUE TITLE
option stdevs() not allowed

### ISSUE THREAD

**Issue by juancaros** [mdroste/stata-binscatter2#5]
I am running the binscatter2 example using the nwls88 data. I get the following message:

. binscatter2 wage tenure, stdevs(3)
option stdevs() not allowed

I have tried in different laptops using different versions of STATA. Any ideas?

**Comment by mdroste** [comment]
Hey Juan,

Sorry for the delay! Version 0.19 (now on Github) fixes this issue. Let me know if you have any problems.

- Mike

**Comment by juancaros** [comment]
Thank you, I will try out as soon as possible. Regards,
