### ISSUE TITLE
Error: } is not a valid command name

### ISSUE THREAD

**Issue by aadityadar** [mdroste/stata-binscatter2#6]
Thanks for developing this program. When I try to use it though I get the following error:
```
Num fes: 1
} is not a valid command name
```

There is, however, no error with `binscatter`. What am I doing wrong? 

Here's a MWE:
```
sysuse auto, clear 
binscatter price mpg, absorb(foreign)
binscatter2 price mpg, absorb(foreign)
```

PS: I am using Stata 15MP on Windows 10. `binscatter2`'s Distribution-Date: 20190710. `ftools`  Distribution-Date: 20190213.

**Comment by mdroste** [comment]
Hey there,

My sincerest apologies for the delay, I was on vacation -- this was an errant typo in the last commit. The issue has been fixed. Let me know if you encounter any difficulties!

Best,
Mike
